update DB

diff --git a/Code/computeSham b/Code/computeSham
--- a/Code/computeSham
+++ b/Code/computeSham
@@ -1,6 +1,22 @@
 cd ~/dev/shambcifesdata/
-IFS='|' read user pw < <( zenity --password --username )
-echo $user $pw
+ENTRY=`zenity --password --username`
+case $? in
+    0)
+        # At this step, you can assign a variable to username's value like this:
+        # VAR_USERNAME=`echo $ENTRY | cut -d'|' -f1`
+        
+        # The result from ENTRY command look like: username|password
+        # This command use to cut the first column -> get username
+        echo "User Name: `echo $ENTRY | cut -d'|' -f1`"
+        
+        # This command use to cut the second column -> get password
+        echo "Password : `echo $ENTRY | cut -d'|' -f2`"
+    ;;
+    1)
+        echo "Stop login.";;
+    -1)
+        echo "An unexpected error has occurred.";;
+esac
 git add .
 git commit -m "update DB"
 git push https://$user:$pw@github.com/millanlaboratory/shambcifesdata.git
